[package]
name = "chessgui"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { version = "3.7" }
chessboard = { git = "https://github.com/kyllingene/chessboard.git" }